on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: hw1
        working-directory: homework1
        run: go run main.go && go test

      - name: hw2
        working-directory: homework2
        run: go run main.go && go test

      - name: hw3
        working-directory: homework3
        run: go run main.go && go test

      - name: hw4
        working-directory: homework4
        run: timeout 20 go run main.go && timeout 20 go test

      - name: hw5 - quick demo
        working-directory: homework5
        run: timeout 20 go run main.go

      - name: hw5
        working-directory: homework5
        run: timeout 180 go test > output.txt && head -n 1000 output.txt && tail -n 1000 output.txt